import { Card, CardContent } from '@/components/ui/card'
import { Scale } from 'lucide-react'

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-primary/5 via-blue-50 to-white">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Hero Section */}
        <div className="text-center mb-8">
          <div className="flex items-center justify-center mb-4">
            <Scale className="h-12 w-12 text-primary mr-3" />
            <h1 className="text-3xl md:text-4xl font-bold text-gray-900">
              Terms & Conditions
            </h1>
          </div>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Please read these terms and conditions carefully before using AI Formulator services.
          </p>
        </div>

        <div className="max-w-4xl mx-auto">
          <Card>
            <CardContent className="p-8">
              <div className="prose prose-gray max-w-none">
                <p className="text-sm text-gray-500 mb-6">
                  <strong>Effective Date:</strong> January 15, 2025<br />
                  <strong>Last Updated:</strong> January 15, 2025
                </p>

                <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Acceptance of Terms</h2>
                <p className="mb-6">
                  By accessing and using AI Formulator ("Service"), you accept and agree to be bound by the terms and 
                  provision of this agreement. If you do not agree to abide by the above, please do not use this service.
                </p>

                <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Service Description</h2>
                <p className="mb-6">
                  AI Formulator provides artificial intelligence-powered chemical formulation recommendations and 
                  access to a database of professional formulations. Our service is designed to assist small business 
                  manufacturers in developing chemical products across various categories including skincare, cleaning 
                  products, and personal care items.
                </p>

                <h2 className="text-2xl font-bold text-gray-900 mb-4">3. AI-Generated Content Disclaimer</h2>
                <p className="mb-6">
                  <strong>Important:</strong> Formulations generated by our AI system are based on available data and 
                  algorithms. While we strive for accuracy, AI-generated formulations:
                </p>
                <ul className="list-disc pl-6 mb-6">
                  <li>May contain errors or inaccuracies</li>
                  <li>Should be thoroughly tested before commercial use</li>
                  <li>Require professional verification for safety and compliance</li>
                  <li>Are not guaranteed to work as intended for all applications</li>
                </ul>

                <h2 className="text-2xl font-bold text-gray-900 mb-4">4. User Responsibilities</h2>
                <p className="mb-4">As a user of AI Formulator, you agree to:</p>
                <ul className="list-disc pl-6 mb-6">
                  <li>Use formulations at your own risk and responsibility</li>
                  <li>Conduct proper testing before commercial production</li>
                  <li>Comply with all local, state, and federal regulations</li>
                  <li>Obtain necessary permits and certifications for your products</li>
                  <li>Not hold AI Formulator liable for any outcomes from using our formulations</li>
                  <li>Use the service only for lawful purposes</li>
                </ul>

                <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Intellectual Property</h2>
                <p className="mb-6">
                  All content, formulations, and materials provided through AI Formulator are for informational 
                  purposes. While you may use the formulations for commercial purposes, the underlying technology, 
                  algorithms, and database remain the intellectual property of AI Formulator.
                </p>

                <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Limitation of Liability</h2>
                <p className="mb-6">
                  AI Formulator shall not be liable for any direct, indirect, incidental, special, or consequential 
                  damages resulting from the use or inability to use our service, including but not limited to:
                </p>
                <ul className="list-disc pl-6 mb-6">
                  <li>Product defects or failures</li>
                  <li>Regulatory non-compliance</li>
                  <li>Business losses or damages</li>
                  <li>Personal injury or property damage</li>
                  <li>Data loss or system failures</li>
                </ul>

                <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Professional Consultation</h2>
                <p className="mb-6">
                  AI Formulator does not provide professional chemical engineering, regulatory, or safety advice. 
                  Users should consult with qualified professionals before implementing any formulations, especially 
                  for products intended for human use or commercial sale.
                </p>

                <h2 className="text-2xl font-bold text-gray-900 mb-4">8. Account and Authentication</h2>
                <p className="mb-6">
                  While browsing is free, access to PDF downloads requires authentication. You are responsible for 
                  maintaining the security of your account credentials. Unauthorized sharing of account access is prohibited.
                </p>

                <h2 className="text-2xl font-bold text-gray-900 mb-4">9. Service Modifications</h2>
                <p className="mb-6">
                  AI Formulator reserves the right to modify, suspend, or discontinue any aspect of the service at any 
                  time without prior notice. We may also update these terms of service as needed.
                </p>

                <h2 className="text-2xl font-bold text-gray-900 mb-4">10. Governing Law</h2>
                <p className="mb-6">
                  These terms shall be governed by and construed in accordance with the laws of the State of California, 
                  United States, without regard to its conflict of law provisions.
                </p>

                <h2 className="text-2xl font-bold text-gray-900 mb-4">11. Contact Information</h2>
                <p className="mb-4">
                  For questions about these Terms & Conditions, please contact us:
                </p>
                <ul className="list-none mb-6">
                  <li><strong>Email:</strong> legal@aiformulator.com</li>
                </ul>

                <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mt-8">
                  <p className="text-sm text-yellow-800">
                    <strong>Important Notice:</strong> These terms are legally binding. By continuing to use AI Formulator, 
                    you acknowledge that you have read, understood, and agree to these terms and conditions.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}