import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

const STORAGE_DIR = path.join(process.cwd(), 'formulation_files');

// Ensure storage directory exists
if (!fs.existsSync(STORAGE_DIR)) {
  fs.mkdirSync(STORAGE_DIR, { recursive: true });
  console.log(`📁 Created formulation files directory: ${STORAGE_DIR}`);
}

export interface StoredFile {
  path: string;
  filename: string;
}

/**
 * Save a PDF file to disk
 */
export function savePDFFile(pdfBuffer: Buffer, formulationName: string): StoredFile {
  const sanitizedName = formulationName
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .replace(/\s+/g, '_')
    .substring(0, 50);
  
  const uniqueId = crypto.randomBytes(8).toString('hex');
  const filename = `${sanitizedName}_${uniqueId}.pdf`;
  const filePath = path.join(STORAGE_DIR, filename);
  
  fs.writeFileSync(filePath, pdfBuffer);
  console.log(`✅ PDF saved: ${filename}`);
  
  return {
    path: filePath,
    filename
  };
}

/**
 * Save a text file to disk
 */
export function saveTextFile(content: string, formulationName: string): StoredFile {
  const sanitizedName = formulationName
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .replace(/\s+/g, '_')
    .substring(0, 50);
  
  const uniqueId = crypto.randomBytes(8).toString('hex');
  const filename = `${sanitizedName}_${uniqueId}.txt`;
  const filePath = path.join(STORAGE_DIR, filename);
  
  fs.writeFileSync(filePath, content, 'utf-8');
  console.log(`✅ Text file saved: ${filename}`);
  
  return {
    path: filePath,
    filename
  };
}

/**
 * Generate text content from formulation data
 */
export function generateTextContent(formulation: any): string {
  const {
    name,
    description,
    ingredients,
    instructions,
    usageInstructions,
    phLevel,
    shelfLife,
    viscosity,
    storageConditions,
    batchSize,
    processingTime,
    temperature,
    equipment,
    certification
  } = formulation;
  
  let textContent = '';
  
  textContent += `==============================================\n`;
  textContent += `${name.toUpperCase()}\n`;
  textContent += `==============================================\n\n`;
  
  textContent += `DESCRIPTION:\n${description}\n\n`;
  
  textContent += `INGREDIENTS:\n`;
  const ingredientsList = JSON.parse(ingredients);
  ingredientsList.forEach((ing: any, index: number) => {
    textContent += `${index + 1}. ${ing.name} - ${ing.quantity}\n`;
  });
  textContent += `\n`;
  
  textContent += `PREPARATION INSTRUCTIONS:\n`;
  const instructionsList = JSON.parse(instructions);
  instructionsList.forEach((inst: any, index: number) => {
    textContent += `${index + 1}. ${inst}\n`;
  });
  textContent += `\n`;
  
  textContent += `USAGE INSTRUCTIONS:\n${usageInstructions}\n\n`;
  
  textContent += `TECHNICAL SPECIFICATIONS:\n`;
  textContent += `- pH Level: ${phLevel}\n`;
  textContent += `- Shelf Life: ${shelfLife}\n`;
  if (viscosity) textContent += `- Viscosity: ${viscosity}\n`;
  textContent += `- Storage Conditions: ${storageConditions}\n`;
  textContent += `- Batch Size: ${batchSize}\n`;
  textContent += `- Processing Time: ${processingTime}\n`;
  textContent += `- Temperature: ${temperature}\n`;
  textContent += `\n`;
  
  textContent += `EQUIPMENT REQUIRED:\n${equipment}\n\n`;
  
  if (certification) {
    textContent += `CERTIFICATIONS:\n${certification}\n\n`;
  }
  
  textContent += `==============================================\n`;
  textContent += `Generated by AIFormulator.com\n`;
  textContent += `==============================================\n`;
  
  return textContent;
}

/**
 * Read a file from disk
 */
export function readFile(filename: string): Buffer {
  const filePath = path.join(STORAGE_DIR, filename);
  
  if (!fs.existsSync(filePath)) {
    throw new Error(`File not found: ${filename}`);
  }
  
  return fs.readFileSync(filePath);
}

/**
 * Delete a file from disk
 */
export function deleteFile(filename: string): void {
  const filePath = path.join(STORAGE_DIR, filename);
  
  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
    console.log(`🗑️  File deleted: ${filename}`);
  }
}
