import type { InsertFormulation } from '@shared/schema';

interface FormulationTXTData extends Omit<InsertFormulation, 'categoryId'> {
  ingredients: string;
  instructions: string;
}

export function generateFormulationTXT(formulation: FormulationTXTData): Buffer {
  // Parse JSON strings
  const ingredients = JSON.parse(formulation.ingredients || '[]');
  const instructions = JSON.parse(formulation.instructions || '[]');
  
  const content = `AIFORMULATOR
CHEMICAL FORMULATION REPORT
==========================

Product Name: ${formulation.name || 'Untitled Product'}
Description: ${formulation.description || 'No description provided'}

TECHNICAL SPECIFICATIONS:
========================
pH Level: ${formulation.phLevel || 'Not specified'}
Viscosity: ${formulation.viscosity || 'Not specified'}
Shelf Life: ${formulation.shelfLife || 'Not specified'}
Batch Size: ${formulation.batchSize || 'Not specified'}
Processing Time: ${formulation.processingTime || 'Not specified'}
Temperature: ${formulation.temperature || 'Not specified'}
Storage Conditions: ${formulation.storageConditions || 'Not specified'}
Equipment: ${formulation.equipment || 'Not specified'}
Certification: ${formulation.certification || 'Not specified'}

INGREDIENTS:
===========
${ingredients.map((ingredient: any, index: number) => 
  `${index + 1}. ${ingredient.name || ''} (${ingredient.inci || ''}) - ${ingredient.percentage || ''} - ${ingredient.function || ''}`
).join('\n')}

MANUFACTURING INSTRUCTIONS:
==========================
${instructions.map((phase: any, phaseIndex: number) => 
  `Phase ${phaseIndex + 1}: ${phase.phase || 'Manufacturing Phase'}\n${(phase.steps && Array.isArray(phase.steps)) ? phase.steps.map((step: string, stepIndex: number) => 
    `   ${stepIndex + 1}. ${step}`
  ).join('\n') : ''}`
).join('\n\n')}

USAGE INSTRUCTIONS:
==================
${formulation.usageInstructions || 'No usage instructions provided'}

Generated by AIFormulator
Generated on: ${new Date().toLocaleDateString()}
`;
  
  return Buffer.from(content, 'utf-8');
}