import type { InsertFormulation } from '@shared/schema';

interface FormulationTXTData extends Omit<InsertFormulation, 'categoryId'> {
  ingredients: string;
  instructions: string;
}

export function generateFormulationTXT(formulation: FormulationTXTData): Buffer {
  // Parse JSON strings
  const ingredients = JSON.parse(formulation.ingredients || '[]');
  const instructions = JSON.parse(formulation.instructions || '[]');
  
  const content = `PROFESSIONAL FORMULATION DOCUMENT
==================================

1. TITLE
========
${formulation.name || 'Professional Formulation Document'}

2. SHORT DESCRIPTION
===================
${formulation.description || 'Professional chemical formulation designed for optimal performance and safety.'}

3. TECHNICAL OVERVIEW
====================
Key Features: High-performance formulation with optimal stability and effectiveness.
Performance Claims: Meets industry standards for pH balance, viscosity, and shelf life.
Benefits: ${formulation.usageInstructions ? 'Enhanced performance with proven results.' : 'Designed for professional applications with consistent quality.'}

4. FORMULATION TABLE
===================
Ingredients with INCI name, percentage, and function:
${ingredients.map((ingredient: any, index: number) => 
  `${index + 1}. ${ingredient.name || 'N/A'} (${ingredient.inci || 'N/A'}) - ${ingredient.percentage || 'N/A'}% - ${ingredient.function || 'N/A'}`
).join('\n')}

5. MANUFACTURING PROCESS
=======================
Step-by-step preparation guidelines:
${instructions.map((phase: any, phaseIndex: number) => 
  `Phase ${phaseIndex + 1}: ${phase.phase || 'Manufacturing Phase'}\n${(phase.steps && Array.isArray(phase.steps)) ? phase.steps.map((step: string, stepIndex: number) => 
    `   ${stepIndex + 1}. ${step}`
  ).join('\n') : ''}`
).join('\n\n')}

6. REQUIRED EQUIPMENT
====================
Basic instruments and tools needed:
${formulation.equipment || 'Standard mixing equipment, measuring instruments, pH meter, thermometer, safety equipment'}

7. SAFETY PRECAUTIONS
====================
Handling: Wear appropriate PPE including gloves, safety glasses, and lab coat.
PPE Requirements: Chemical-resistant gloves, safety goggles, protective clothing.
Storage: Store in cool, dry place away from direct sunlight. Keep containers tightly closed.
Storage Conditions: ${formulation.storageConditions || 'Store at room temperature (15-25°C)'}

8. QUALITY TESTING & STANDARDS
==============================
Suggested checks:
- pH Testing: Target pH ${formulation.phLevel || '6.5-7.5'}
- Viscosity: ${formulation.viscosity || 'As specified in technical parameters'}
- Stability Testing: Accelerated aging and thermal cycling tests
- Microbial Testing: Preservative efficacy and contamination screening
- Performance Testing: Product-specific functionality verification

9. PACKAGING & REGULATORY NOTES
===============================
Packaging: Use chemically compatible containers (HDPE, glass, or PET).
Labeling: Include product name, ingredients, usage instructions, and safety warnings.
Regulatory Compliance: Ensure compliance with local regulations and safety standards.
Certification: ${formulation.certification || 'Follow applicable industry standards and regulations'}
Documentation: Maintain batch records and quality control documentation.

10. SCALING NOTE
===============
Lab Scale: This formulation is designed for laboratory testing and development.
Pilot Scale: For pilot production, scale proportionally and verify all parameters.
Production Scale: Consider equipment limitations, mixing efficiency, and process validation.
Batch Size: Current formulation is optimized for ${formulation.batchSize || 'laboratory scale'}.
Scaling Factor: Maintain ingredient ratios while adjusting processing parameters as needed.

Generated by AIFormulator
Generated on: ${new Date().toLocaleDateString()}
`;
  
  return Buffer.from(content, 'utf-8');
}